export const motibharatPromptV1 = `Create an image in the authentic visual grammar of traditional Moti Bharat beadwork from Gujarat. Do not treat this as generic bead embroidery, generic jewelry, or a normal world with beads added later. Build the entire image as if it is generated by a Moti Bharat world where bead-by-bead surface construction, dense contour-led relief, and rhythmic color-blocking control every decision.

The image must obey Moti Bharat rules:
- the world is built from bead-density logic: surfaces are formed by the physical placement of tiny, uniform, opaque glass beads
- motifs are not painted or printed; they are constructed through color-blocked bead clusters
- the visual field must feel tactile, relief-based, and defined by the "pixel-like" accumulation of beads
- contours are not lines; they are rows of beads that define edges and interior masses
- traditional motifs (torans, animals, flowers, geometric patterns) must behave as structural beadwork units
- the world feels vibrant, ceremonial, and physically substantial due to the weight and texture of beads

Translate the full world through this style:
- shape must become bead-accumulated, contour-defined, and color-blocked
- form must become a relief surface of uniform glass beads rather than smooth realism
- space must become textile-space: defined by bead-grids and surface-massing rather than ordinary perspective space
- light must reveal the individual bead highlights, the matte or lustrous quality of glass, and the specific texture of bead rows
- shadow must support the physical relief of the beadwork layers, not cinematic atmosphere
- value must remain clean, contrasting (bead-on-bead), and motif-supportive
- volume must behave as beadwork volume: stiff, dense, and physically layered
- movement must feel like the rhythmic repetition of beads, the sway of fringed edges, and tactile continuity
- environment must also obey Moti Bharat order: architecture, foliage, ground, and background must all feel built from bead rows and color-blocked clusters

Use Moti Bharat anchors such as:
tiny uniform beads, dense color-blocked motifs (elephants, parrots, swastikas), bead-fringe details, the specific "pixelated" quality of bead construction, and the vibrant palette of traditional Gujarati beadwork.

Avoid:
generic beaded fashion, single-material logic, scattered beads on normal surfaces, ordinary environment with only the textile changed, surface-only transformation.

The final result must feel like a true Moti Bharat world: bead-built, dense-relief, color-blocked, and fully translated in shape, form, space, light, hierarchy, and environment.`;