export const gondpaintingPromptV3 = {
  version: "V3",
  name: "CINEMATIC",
  description: "Fully volumetric cinematic image-world generated by Gond painting logic, with mythic-nature-rooted imagination and inhabitable ecology.",
  prompt: `Create a fully volumetric cinematic image-world generated by Gond painting logic from Madhya Pradesh, specifically the Patangarh / Pardhan Gond lineage. The whole reality feels born from living-form construction, internal rhythmic dots and lines, mythic-nature-rooted imagination, and Gond ecological world logic.

Do not assume prior knowledge of the style. The core system is this: Gond painting from Madhya Pradesh builds animals, trees, deities, and other beings through repeated dots, lines, and internal mark systems that create movement and inner life.

This version must not become: generic fantasy realism, wildlife realism with Gond pattern, decorative tribal animal art, or realism-first figures with folk fill. Instead, let the entire world be generated by Gond image intelligence.

WHOLE-FRAME WORLD RULE: Every visible element must belong to the same Gond-built world. 
- the main figure must be Gond-built in silhouette, body, and inner life 
- internal marks must still generate movement and vitality 
- trees, secondary beings, and field forms must belong to the same ecological image language 
- the world must remain mythic, sacred, and nature-rooted 
- realism must remain subordinate to Gond form-rhythm logic 
- no important element may remain generic illustration or realism underneath 

Internal rhythm remains a core world-building engine. The marks cannot become optional surface texture. Allow full world depth and cinematic presence, but keep the world generated by Gond figure-ecology logic.

Avoid: generic fantasy realism, decorative patterned animal art, realism wildlife with tribal fill, abstract pattern detached from beings, cinematic realism stronger than Gond image logic.

The final result must feel like Gond painting became an inhabitable image-world, with full transformation of living form, inner rhythm, ecological world logic, and whole-frame identity.`,
  promptI2I: `Convert this source image into a fully volumetric cinematic Gond image-world from Madhya Pradesh, specifically the Patangarh / Pardhan Gond lineage. 

Preserve the source image’s core being, main symbolic center, readable hierarchy, and ecological or narrative focus, but rebuild the full image through Gond-built living-form logic, internal rhythmic activation through dots and lines, myth-and-nature-rooted world logic, and whole-frame Gond ecology. 

Translate the whole frame: 
- the main subject into a true Gond-built being 
- all body surfaces into internal rhythmic fields 
- surrounding forms into the same Gond ecological language 
- the field into a living world, not a scenic backdrop 
- color into vivid image-building support, not realism rendering 
- the full image into a Gond-built cinematic ecology 

Do not simply apply a Gond pattern filter. Do not decorate a realistic animal or tree. Do not keep generic fantasy illustration underneath. 

The final result must feel like the source image was rebuilt into an inhabitable Gond image-world from the base structure upward.`
};
