/** @type {import('next-sitemap').IConfig} */
const isProd = process.env.NODE_ENV === 'production';
const siteUrl = process.env.SITE_URL || 'https://wildmindai.com';

// Import blog posts to generate dynamic URLs
// Use pre-generated JSON file for sitemap data (generated by generateBlogSitemapData.js)
let blogPosts = [];
try {
  // Try to load the pre-generated JSON file first (preferred method)
  const sitemapDataPath = require.resolve('./src/app/blog/data/blogPosts.sitemap.json');
  const sitemapData = require(sitemapDataPath);
  blogPosts = sitemapData || [];
  console.log(`✅ Loaded ${blogPosts.length} blog posts from sitemap data file`);
} catch (jsonError) {
  // Fallback: Try to load TypeScript file directly (requires tsx)
  try {
    const { register } = require('tsx/cjs/api');
    register();
    const blogModule = require('./src/app/blog/data/blogPosts.ts');
    blogPosts = (blogModule.blogPosts || []).map(post => ({
      id: post.id,
      publishedAt: post.publishedAt || null,
      updatedAt: post.updatedAt || null,
      createdAt: post.createdAt || null,
    }));
    console.log(`✅ Loaded ${blogPosts.length} blog posts from TypeScript file (fallback)`);
  } catch (tsError) {
    console.error('❌ Error loading blog posts for sitemap:', tsError.message);
    console.warn('⚠️  Sitemap will be generated without blog posts.');
    console.warn('💡 Run "npm run prebuild" to generate sitemap data file.');
    blogPosts = [];
  }
}

// ONLY PUBLIC PAGES - Google can crawl these without authentication
// PRIORITY ORDER: Landing → Blog → Pricing → ArtStation → Legal
const canonicalPages = [
  // ===== TIER 1: Main Landing (Highest Priority) =====
  { url: '/', priority: 1.0, changefreq: 'daily' },
  { url: '/view/Landingpage', priority: 0.95, changefreq: 'daily' },
  
  // ===== TIER 2: Canvas Landing (High Priority) =====
  { url: '/canvas-projects', priority: 0.9, changefreq: 'daily' },
  
  // ===== TIER 3: Blog (High Priority for SEO) =====
  { url: '/blog', priority: 0.9, changefreq: 'daily' },

  
  // Blog posts will be added here dynamically (priority 0.75)
  
  // ===== TIER 3: Key Public Pages =====
  { url: '/view/pricing', priority: 0.85, changefreq: 'daily' },
  { url: '/view/ArtStation', priority: 0.8, changefreq: 'daily' },
  
  // ===== TIER 4: Company & Product Pages =====
  { url: '/company/about', priority: 0.6, changefreq: 'daily' },
  { url: '/company/contact-us', priority: 0.6, changefreq: 'daily' },
  { url: '/company/newsletter', priority: 0.5, changefreq: 'daily' },
  { url: '/product/faqs', priority: 0.7, changefreq: 'daily' },
  
  // ===== TIER 5: Legal Pages (Lower Priority) =====
  { url: '/legal', priority: 0.3, changefreq: 'daily' },
  { url: '/legal/privacy', priority: 0.3, changefreq: 'daily' },
  { url: '/legal/terms', priority: 0.3, changefreq: 'daily' },
  { url: '/legal/cookie', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/aup', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/dmca', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/api-terms', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/terms-conditions', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/cancellation-refunds', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/shipping', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/relationship', priority: 0.2, changefreq: 'daily' },
  { url: '/legal/thirdparty', priority: 0.2, changefreq: 'daily' },
];

// Add all blog posts dynamically - TIER 2 priority (after /blog main page)
// Include lastmod date if available in blog post data
blogPosts.forEach((post) => {
  canonicalPages.splice(3, 0, { // Insert after /blog main page at index 3
    url: `/blog/${post.id}`,
    priority: 0.75,
    changefreq: 'weekly', // Blog posts change less frequently than daily pages
    lastmod: post.publishedAt || post.updatedAt || post.createdAt || new Date().toISOString(),
  });
});

// Create a map of URL to page config for quick lookup
const canonicalMap = new Map(canonicalPages.map(page => [page.url, page]));

module.exports = {
  siteUrl,
  outDir: './public',
  generateRobotsTxt: true,
  changefreq: 'daily', // Default to daily for everything
  priority: 0.7,
  sitemapSize: 5000,
  exclude: [
    // AUTHENTICATED PAGES (Google can't crawl these)
    '/edit-image',
    '/edit-image/*',
    '/edit-video',
    '/edit-video/*',
    '/text-to-image',
    '/text-to-image/*',
    '/text-to-video',
    '/text-to-video/*',
    '/image-to-video',
    '/image-to-video/*',
    '/text-to-music',
    '/text-to-music/*',
    '/logo',
    '/logo/*',
    '/logo-generation',
    '/logo-generation/*',
    '/sticker-generation',
    '/sticker-generation/*',
    '/mockup-generation',
    '/mockup-generation/*',
    '/product-generation',
    '/product-generation/*',
    '/ad-generation',
    '/ad-generation/*',
    '/live-chat',
    '/live-chat/*',
    
    // USER PAGES (authenticated)
    '/view/HomePage',
    '/view/HomePage/*',
    '/view/editimage',
    '/view/editimage/*',
    '/view/EditImage',
    '/view/EditImage/*',
    '/view/editvideo',
    '/view/editvideo/*',
    '/view/EditVideo',
    '/view/EditVideo/*',
    '/view/Generation/*',
    '/history',
    '/history/*',
    '/bookmarks',
    '/bookmarks/*',
    '/account-management',
    '/view/account-management',
    '/view/account-management/*',
    
    // AUTH PAGES
    '/auth/*',
    '/signup',
    '/signup/*',
    '/login',
    '/login/*',
    '/view/signup',
    '/view/login',
    '/forgot-password',
    
    // SYSTEM PAGES
    '/admin/*',
    '/api/*',
    '/temp/*',
    '/_next/*',
    '/404',
    '/favicon.ico',
    '/robots.txt',
    
    // DISABLED FEATURES
    '/view/workflows',
    '/view/workflows/*',
    '/view/Generation/wildmindskit/*',
  ],
  robotsTxtOptions: {
    policies: isProd
      ? [{
          userAgent: '*',
          allow: '/',
          disallow: [
            '/admin/',
            '/api/',
            '/_next/',
            '/auth/',
            '/history',
            '/bookmarks',
            '/account-management',
            '/signup',
            '/login',
            '/edit-image',
            '/edit-video',
            '/text-to-image',
            '/text-to-video',
            '/text-to-music',
            '/logo-generation',
            '/view/HomePage',
            '/view/EditImage',
            '/view/EditVideo',
            '/view/Generation',
          ],
        }]
      : [{ userAgent: '*', disallow: '/' }],
  },
  additionalPaths: async (config) => {
    // Explicitly add blog post URLs since next-sitemap doesn't auto-discover dynamic routes
    const blogPostPaths = blogPosts.map((post) => ({
      loc: `/blog/${post.id}`,
      changefreq: 'weekly',
      priority: 0.75,
      lastmod: post.publishedAt || post.updatedAt || post.createdAt || new Date().toISOString(),
    }));
    
    return blogPostPaths;
  },
  transform: async (config, path) => {
    const pageConfig = canonicalMap.get(path);
    if (!pageConfig) {
      // Reject other discovered pages (they're likely authenticated)
      return null;
    }
    return {
      loc: path,
      changefreq: pageConfig.changefreq || 'daily',
      priority: pageConfig.priority || config.priority,
      lastmod: pageConfig.lastmod || new Date().toISOString(),
    };
  },
};
