export const moirangpheePromptV1 = `Create an image in the authentic visual grammar of traditional Moirang Phee from Manipur. Do not treat this as generic cotton handloom, generic Manipuri weaving, or a normal world with Moirang Phee fabric added later. Build the entire image as if it is generated by a Moirang Phee world where the Moirang Pheejin border motif (the sharp, triangular "yarong" teeth), extra-weft woven logic, and the Pakhangba symbolic hierarchy control every decision.

The image must obey Moirang Phee rules:
- the world is built from border-field logic: the Moirang Pheejin border is not an edge; it is the structural authority of the cloth
- motifs are built through extra-weft technique: they must feel like they are "woven-in" with distinct, sharp, step-like triangular shapes (odd-step discipline)
- the field must feel airy, fine, and translucent (characteristic of "phee"), yet the extra-weft borders must feel substantial and structurally firm
- the sharp triangular "teeth" of the Moirang Pheejin motif must point toward the body-field, never outward
- the world reads as sacred, symbolic (linked to Princess Thoibi), and structurally precise
- the color palette remains traditional: white or off-white grounds with vibrant red, black, or indigo borders

Translate the full world through this style:
- shape must become border-led, triangular-stepped, and field-oriented
- form must become fine-woven and extra-weft-disciplined rather than pictorial or generic realism
- space must become textile-space: divided into structural border-zones and delicate body-fields rather than ordinary perspective space
- light must reveal the extra-weft thread relief, the fine translucency of the base weave, and the sharp clarity of the triangular motifs
- shadow must support the woven relief and the symbolic structural divisions, not cinematic atmosphere
- value must remain clean, contrasting (motif against ground), and hierarchy-supportive
- volume must behave as Moirang Phee cloth volume: light folds, delicate drape, and the specific tension of extra-weft borders
- movement must feel like the flow of fine Manipuri cotton, the rhythm of woven "teeth", and symbolic continuity
- environment must also obey Moirang Phee order: architecture, foliage, ground, and background must all feel organized by border hierarchy, sharp triangular geometry, and the material presence of extra-weft fields

Use Moirang Phee anchors such as:
Moirang Pheejin (teeth-like border), sharp odd-step triangular motifs, fine white phee translucency, extra-weft relief, and Meitei courtly/sacred dignity.

Avoid:
generic tribal weaving, soft-edged motifs, printed triangles, single-material logic, ordinary environment with only the textile changed, surface-only transformation.

The final result must feel like a true Moirang Phee world: border-led, extra-weft-disciplined, sharp-triangular, and fully translated in shape, form, space, light, hierarchy, and environment.`;