export const rosewoodinlayPromptV1 = `Create an image in the authentic visual grammar of traditional Mysuru Rosewood Inlay from Karnataka. Do not treat this as generic wood carving, generic marquetry, or a normal world with wood textures added later. Build the entire image as if it is generated by a Rosewood Inlay world where the dark rosewood base, contrasting material inserts (ivory-substitutes, colored wood), and fitted-recess logic control every decision.

The image must obey Rosewood Inlay rules:
- the world is built from base-and-insert logic: the image is not a surface; it is a dark rosewood (Dalbergia latifolia) substrate into which contrasting shapes are physically fitted
- shapes are not painted; they are discrete cutouts (ivory-colored or other woods) with sharp, clean boundaries that fit perfectly into the rosewood recesses
- the visual field is defined by the deep, dark, grainy character of rosewood against the smooth, matte or polished contrast of the inserts
- contours are the physical seams where base and insert meet
- traditional motifs (landscapes, court scenes, birds, animals, floral borders) must behave as structural inlay units
- the world feels heavy, durable, and precisely crafted through physical assembly

Translate the full world through this style:
- shape must become contrast-separated, fitted, and inlay-born
- form must become a flush-surface interaction of dark wood and light inserts rather than generic 3D realism
- space must become pictorial-space: organized by composed planes and decorative borders (friezes) rather than ordinary perspective space
- light must reveal the beautiful dark grain and natural oil of rosewood, and the smooth, distinct texture of the fitted inserts
- shadow must support the sense of a flush surface and minimal relief at the seams, not cinematic atmosphere
- value must remain starkly contrasting (dark base vs light insert) and hierarchy-supportive
- volume must behave as inlay volume: defined by the grain-direction of the wood pieces and the boundary-led masses
- movement must feel like the rhythmic repetition of inlaid units and the flow of natural wood grain
- environment must also obey Rosewood Inlay order: architecture, foliage, ground, and background must all feel built from fitted wooden pieces and contrast-led assembly

Use Rosewood Inlay anchors such as:
deep dark rosewood base, contrasting ivory-white or colored wood inserts, sharp fitted seams, traditional frieze borders, the specific Mysurean classical imagery, and the visible grain-logic of wood.

Avoid:
generic wooden illustration, wood-textured paintings, crude marquetry, ordinary realism with wood filters, surface-only contrast, decorative lighting on non-inlay surfaces.

The final result must feel like a true Rosewood Inlay world: base-and-insert-driven, dark-wood-led, contrast-fitted, and fully translated in shape, form, space, light, hierarchy, and environment.`;