import { CREATIVE_STYLE_IMAGE_BASE } from "@/constants/creativeStyleCdn";

export type StyleItem = {
  id: string;
  state: string;
  typeId: string;
  name: string;
  title: string;
  desc: string;
  image: string;
  tag: string;
  titleColor: string;
  href: string;
  imageFilter?: string;
};

type RawStyleItem = Omit<StyleItem, "state" | "typeId"> & {
  state?: string;
  typeId?: string;
};

const inferStyleState = (name: string) => name.split(" (")[0].trim();
const inferStyleTypeId = (tag: string) =>
  tag
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

export { CREATIVE_STYLE_IMAGE_BASE };

const rawStyles: RawStyleItem[] = [
  {
    id: "Maharashtra",
    name: "Maharashtra",
    title: "Warli",
    desc: "Warli art is a traditional folk style from India that uses basic geometric shapes, like triangles, circles, and lines, to create stick-figure depictions of daily social life and nature",
    image: `${CREATIVE_STYLE_IMAGE_BASE}warlistyles/warlistyle.png`,
    tag: "Film",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.9)",
  },
  {
    id: "ajrakh",
    name: "Gujarat",
    title: "AJRAKH",
    desc: "A resist block-print textile tradition known for its geometric symmetry, deep indigo tones, and structured border-field composition.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}ajrakh.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.88) saturate(0.95)",
  },
  {
    id: "jhajjar",
    name: "Haryana",
    title: "JHAJJAR POTTERY",
    desc: "A traditional terracotta pottery system centered on functional water vessels, known for its slim-necked surahi forms and porous clay body.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}jhajjar-pottery.avif`,
    tag: "Pottery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "kaavi",
    name: "Goa",
    title: "KAAVI ART",
    desc: "An incised wall art tradition where designs are carved into a red-oxide layer to reveal white lime plaster beneath.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}kaavi-art.avif`,
    tag: "Wall Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "kangra",
    name: "Himachal Pradesh",
    title: "KANGRA",
    desc: "A lyrical miniature painting tradition known for its serene figures, delicate lines, and lush green landscapes expressing poetic and devotional themes.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}kangra.avif`,
    tag: "Miniature",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "karepa",
    name: "Goa",
    title: "KAREPA WINDOWS",
    desc: "A traditional window system where translucent shell panes replace glass, filtering light while maintaining privacy and softness.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}karepa-windows.avif`,
    tag: "Window",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "khatwa",
    name: "Bihar",
    title: "KHATWA APPLIQUÉ",
    desc: "A traditional textile art where colored fabric shapes are cut and stitched onto a base cloth to create bold narrative compositions.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}khatwa-appliqu.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "khovar",
    name: "Jharkhand",
    title: "KHOVAR",
    desc: "A ceremonial wall art created by etching through layered clay surfaces, revealing motifs in striking black-and-white contrast.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}khovar.avif`,
    tag: "Wall Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "kinnauri",
    name: "Himachal Pradesh",
    title: "KINNAURI SHAWL",
    desc: "A handwoven wool textile known for its intricate geometric motifs, strong border design, and symbolic pattern structure.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}kinnauri-shawl.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "kosa",
    name: "Chhattisgarh",
    title: "KOSA SILK",
    desc: "A traditional handloom silk crafted from Kosa fibers, known for its natural texture, breathable weave, and subtle golden sheen.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}kosa-silk.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "kutch",
    name: "Gujarat",
    title: "KUTCH EMBROIDERY",
    desc: "A traditional hand embroidery system defined by region-specific styles, dense stitchwork, and richly detailed surface patterns built directly into fabric.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}kutch-embroidery.avif`,
    tag: "Embroidery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "lippan",
    name: "Gujarat",
    title: "LIPPAN KAAM",
    desc: "A traditional mud-relief wall craft known for its sculpted patterns and embedded mirrors that reflect light within earthen surfaces.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}lippan-kaam.avif`,
    tag: "Wall Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "majuli",
    name: "Assam",
    title: "MAJULI MASK",
    desc: "A devotional theatre mask tradition used in Bhaona performances, designed for bold character expression and stage readability.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}majuli-mask.avif`,
    tag: "Mask",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "manjusha",
    name: "Bihar (Bhagalpur)",
    title: "MANJUSHA ART",
    desc: "A ritual narrative painting tradition centered on the Bihula-Bishahari story, using bold outlines, flat colors, and symbolic serpent imagery.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}manjusha-art.avif`,
    tag: "Ritual Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "matanipachedi",
    name: "Gujarat",
    title: "MATA NI PACHEDI",
    desc: "A sacred shrine-cloth tradition where the Mother Goddess is depicted within a ritual enclosure using block-print and hand-painted techniques.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}mata-ni-pachedi.avif`,
    tag: "Shrine Cloth",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "madhubani",
    name: "Bihar",
    title: "MADHUBANI",
    desc: "A traditional Mithila painting style known for its bold outlines, symbolic motifs, and richly filled compositions with no empty space.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}madhubani.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.98)",
  },
  {
    id: "kyilkhor",
    name: "Arunachal Pradesh",
    title: "KYIL-KHOR",
    desc: "A sacred Buddhist mandala system representing a structured cosmic diagram with central hierarchy, symbolic geometry, and ritual significance.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}kyil-khor.avif`,
    tag: "Sacred",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sherdukpen",
    name: "Arunachal Pradesh",
    title: "SHERDUKPEN TEXTILE",
    desc: "A handwoven textile tradition known for its centered motifs, white-ground structure, and functional woven forms used as carrying cloths.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}sherdukpen-textile.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "idumishmi",
    name: "Arunachal Pradesh",
    title: "IDU MISHMI TEXTILE",
    desc: "A handwoven textile tradition known for its bold geometric patterns, diamond motifs, and dense loom-based craftsmanship.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}idu-mishmi-textile.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "etikoppaka",
    name: "Andhra Pradesh",
    title: "ETIKOPPAKA TOYS",
    desc: "A traditional lacquered wood craft known for its smooth turned forms, vibrant natural colors, and refined handcrafted finish",
    image: `${CREATIVE_STYLE_IMAGE_BASE}etikoppaka-toys.avif`,
    tag: "Toy",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.98)",
  },
  {
    id: "kondapalli",
    name: "Andhra Pradesh",
    title: "KONDAPALLI TOYS",
    desc: "A traditional wooden toy craft known for its hand-carved forms, vibrant painted surfaces, and charming miniature storytelling scenes.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}kondapalli-toys.avif`,
    tag: "Toy",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.98)",
  },
  {
    id: "monpamask",
    name: "Arunachal Pradesh",
    title: "MONPA MASK",
    desc: "A ritual woodcraft tradition known for its symbolic carved masks, bold expressions, and ceremonial significance in cultural performances.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}monpa-mask.avif`,
    tag: "Ritual",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "handmadepaper",
    name: "Arunachal Pradesh",
    title: "HANDMADE PAPER",
    desc: "A traditional bark-fiber paper craft known for its natural texture, matte finish, and quiet material elegance rooted in handmade processes.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}handmade-paper.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "monpa",
    name: "Arunachal Pradesh",
    title: "MONPA TEXTILE",
    desc: "A handwoven textile tradition defined by rhythmic patterns, banded structures, and deeply rooted loom-based craftsmanship.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}monpa-textile.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "wancho",
    name: "Arunachal Pradesh",
    title: "WANCHO CARVING",
    desc: "A traditional wood carving practice known for its bold, head-centric forms, symbolic expressions, and deeply carved handcrafted textures.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}wancho-carving.avif`,
    tag: "Sculpture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "thangka",
    name: "Arunachal Pradesh",
    title: "THANGKA",
    desc: "A sacred Buddhist scroll painting tradition known for its precise iconography, spiritual symbolism, and intricate hand-painted detailing on cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}sacred-thangka-art.avif`,
    tag: "Sacred",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "tholu",
    name: "Andhra Pradesh",
    title: "LEATHER PUPPETRY",
    desc: "A traditional shadow theatre art crafted from translucent leather, known for its intricate perforations, vibrant colors, and dramatic backlit storytelling.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}andra-leather.avif`,
    tag: "Theatre",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "uppadajamdani",
    name: "Andhra Pradesh",
    title: "UPPADA JAMDANI",
    desc: "A delicate handwoven textile known for its extra-weft motif seamlessly integrated into the fabric, creating lightweight and elegant designs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}uppada-jamdani.avif`,
    tag: "Fabric",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.9)",
  },
  {
    id: "srikalahasti",
    name: "Andhra Pradesh",
    title: "SRIKALAHASTI",
    desc: "A sacred hand-painted Kalamkari tradition known for its expressive freehand drawings, mythological storytelling, and natural dye detailing on cotton cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}srikalahasti-kalamkari.avif`,
    tag: "Fabric",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.9)",
  },
  {
    id: "machilipatnam",
    name: "Andhra Pradesh",
    title: "MACHILIPATNAM",
    desc: "A block-printed Kalamkari style featuring intricate Persian-inspired floral patterns, repeat motifs, and natural dyes crafted for textile design.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}machilipatnam-kalamkari.avif`,
    tag: "Fabric",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.9)",
  },
  {
    id: "asharikandi",
    name: "Assam",
    title: "ASHARIKANDI TERRACOTTA",
    desc: "A traditional fired-clay craft from Assam, where handmade terracotta forms are shaped, dried, and fired into earthy, matte objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}asharikandi-terracotta.avif`,
    tag: "Sculpture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "azulejos",
    name: "Goa",
    title: "AZULEJOS",
    desc: "A hand-painted ceramic tile tradition featuring blue-on-white imagery, decorative borders, and architectural plaque compositions.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}azulejos1.avif`,
    tag: "Ceramic",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.95) saturate(0.9)",
  },
  {
    id: "bandhani",
    name: "Gujarat",
    title: "BANDHANI",
    desc: "A resist-dye textile tradition created through thousands of hand-tied points, forming intricate dot patterns and vibrant ceremonial cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}bandhani.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(1.1)",
  },
  {
    id: "bastardhokra",
    name: "Chhattisgarh",
    title: "BASTAR DHOKRA",
    desc: "A traditional lost-wax metal casting craft where objects are built in wax and transformed into intricate bell-metal forms.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}bastar-dhokra.avif`,
    tag: "Metalcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(1)",
  },
  {
    id: "muriawallpainting",
    name: "Chhattisgarh (Bastar)",
    title: "MURIA WALL PAINTING",
    desc: "A traditional earthen mural art where symbolic figures are painted onto prepared mud walls using natural pigments and communal storytelling.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}muria-wall-painting.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "bastarwoodcraft",
    name: "Chhattisgarh",
    title: "BASTAR WOODCRAFT",
    desc: "A traditional hand-carved woodcraft where solid blocks are shaped into symbolic figures using simple tools and techniques.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}bastar-woodcraft.avif`,
    tag: "Woodcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "bhagalpursilk",
    name: "Bihar",
    title: "BHAGALPUR SILK",
    desc: "A handloom silk tradition known for its tussar-based texture, breathable weave, and soft natural lustre.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}bhagalpur-silk.avif`,
    tag: "Fabric",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "chambaminiature",
    name: "Himachal Pradesh",
    title: "CHAMBA MINIATURE",
    desc: "A court painting tradition known for its narrative scenes, stylized figures, and refined use of color in miniature form.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}chamba-miniature.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "exposedlaterite",
    name: "Goa",
    title: "EXPOSED LATERITE",
    desc: "A construction system using cut laterite stone blocks, where exposed red-brown masonry defines the structure and character of buildings.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}exposed-laterite.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "gharchola",
    name: "Gujarat",
    title: "GHARCHOLA",
    desc: "A ceremonial bridal textile defined by its gold zari grid, Bandhani-filled squares, and structured red-gold design rooted in wedding traditions.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}gharchola.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(1.1)",
  },
  {
    id: "godnaart",
    name: "Bihar (Mithila)",
    title: "GODNA ART",
    desc: "A tattoo-derived painting tradition where symbolic motifs and repeated marks form inscribed visual narratives.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}godna-art.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "taiahommanuscript",
    name: "Assam",
    title: "TAI-AHOM MANUSCRIPT",
    desc: "A traditional manuscript system where script, symbols, and images coexist to preserve knowledge on folio surfaces.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}tai-ahom-manuscript.avif`,
    tag: "Manuscript",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "tangaliya",
    name: "Gujarat",
    title: "TANGALIYA",
    desc: "A unique handwoven textile tradition where raised bead-like dots are created through extra-weft weaving, forming rhythmic geometric patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}tangaliya.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "agrarianindustrial",
    name: "Haryana",
    title: "AGRARIAN–INDUSTRIAL BLEND",
    desc: "A production ecosystem where agriculture, machinery, and industry operate together within a unified landscape.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}agrarian-industrial-blend.avif`,
    tag: "Ecosystem",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "indoportuguese",
    name: "Goa",
    title: "INDO-PORTUGUESE",
    desc: "A distinctive house-front architecture where bold wall colors, white trim, and structured façades define the identity of Goan streets.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}indo-portuguese.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "tikuliart",
    name: "Bihar (Patna)",
    title: "TIKULI ART",
    desc: "A precision-painted decorative art derived from the bindi tradition, known for its polished surface and fine enamel detailing.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}tikuli-art.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "sohraikhovar",
    name: "Jharkhand",
    title: "SOHRAI–KHOVAR",
    desc: "A traditional wall art practice where mud-house surfaces are transformed into ritual murals using natural pigments and symbolic motifs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}sohrai-khovar.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "woodtemplecarving",
    name: "Himachal Pradesh",
    title: "WOOD TEMPLE CARVING",
    desc: "A sacred architectural carving tradition where wooden temple structures are intricately sculpted with relief and iconographic detail.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}wood-temple-carving.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.9)",
  },
  {
    id: "neoagrarianbrutalism",
    name: "Haryana",
    title: "NEO-AGRARIAN BRUTALISM",
    desc: "A hybrid landscape where cultivated farmland and raw concrete infrastructure merge into a single working production system.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}neo-agrarian-brutalism.avif`,
    tag: "Concept",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "patola",
    name: "Gujarat",
    title: "PATOLA",
    desc: "A double ikat silk weaving tradition where intricate patterns are pre-dyed into threads and precisely aligned during weaving.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}patola.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "phulkari",
    name: "Haryana (Phulkari Belt)",
    title: "PHULKARI",
    desc: "A traditional khaddar-based embroidery where silk threads build patterns through reverse darning, forming ceremonial and heirloom textiles.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}phulkari.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pithora",
    name: "Gujarat",
    title: "PITHORA",
    desc: "A ritual wall painting tradition of the Rathwa community, where sacred horses and deities are painted as part of vow-fulfillment ceremonies.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}pithora.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "roganart",
    name: "Gujarat (Kutch)",
    title: "ROGAN ART",
    desc: "A rare oil-paste textile art where intricate designs are drawn using a stylus and mirrored to create symmetrical compositions on dark cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}rogan-art.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "ruralfibercraft",
    name: "Haryana",
    title: "RURAL FIBER CRAFT",
    desc: "A traditional construction system using reed and rope, where tension, binding, and structural weaving create functional everyday objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}rural-fiber-craft.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sarkandaarchitecture",
    name: "Haryana",
    title: "SARKANDA ARCHITECTURE",
    desc: "A traditional reed-and-thatch shelter system designed for climate responsiveness, using layered roofs and breathable walls for natural cooling.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}sarkanda-architecture.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "shimplahastkala",
    name: "Goa",
    title: "SHIMPLA HASTKALA",
    desc: "A traditional shell craft where natural sea shells are assembled into decorative and functional objects through handcrafted techniques.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}shimpla-hastkala.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sitalpati",
    name: "Assam",
    title: "SITALPATI",
    desc: "A traditional cool mat weaving craft using finely processed murta cane, known for its smooth surface and flat interlaced structure.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}sitalpati.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sohrai",
    name: "Jharkhand",
    title: "SOHRAI",
    desc: "A ritual wall painting tradition where mud-house surfaces are transformed using natural earth pigments into living murals of animals, plants, and harvest life.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}sohrai.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sonowaltextile",
    name: "Assam",
    title: "SONOWAL TEXTILE",
    desc: "A community-specific handloom tradition defined by woven borders, rhythmic bands, and identity-driven textile design.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}sonowal-textile.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sufembroidery",
    name: "Gujarat",
    title: "SUF EMBROIDERY",
    desc: "A counted embroidery tradition built through triangular geometry, where patterns emerge from precise stitching rather than pre-drawn design.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}suf-embroidery.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "katabapplique",
    name: "Gujarat",
    title: "KATAB APPLIQUÉ",
    desc: "A traditional textile craft where cut fabric pieces are stitched onto a base cloth to create bold geometric compositions.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/katab-appliqu.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "baghprint",
    name: "Madhya Pradesh",
    title: "BAGH PRINT",
    desc: "A traditional hand block-printing craft known for its natural red and black dyes, repeat patterns, and textile-based design structure.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/bagh-print.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bamboocraft",
    name: "Meghalaya",
    title: "BAMBOO CRAFT",
    desc: "A traditional craft where split bamboo strips are woven and bound into lightweight, functional structures.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/bamboo-craft.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "nagabeadcluster",
    name: "Nagaland",
    title: "NAGA BEAD CLUSTER",
    desc: "A traditional ornament system where layered bead strands form dense, tiered clusters across the neck and chest.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/naga-bead-cluster.avif`,
    tag: "Ornament",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bidriware",
    name: "Karnataka (Bidar)",
    title: "BIDRIWARE",
    desc: "A traditional metal craft where silver is inlaid into engraved grooves on a deep black alloy surface, creating striking contrast-driven designs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/bidriware.avif`,
    tag: "Metalwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bordersigntextile",
    name: "Manipur",
    title: "BORDER-SIGN TEXTILE",
    desc: "A traditional textile system where meaning is defined through the relationship between a restrained field and a strong identity-bearing border.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/border-sign-textile.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bundelipainting",
    name: "Madhya Pradesh (Orchha)",
    title: "BUNDELI PAINTING",
    desc: "A traditional mural art where clustered scenes depict courtly, devotional, and everyday life using bold colors and narrative composition.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/bundeli-painting.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "ceremonialemblem",
    name: "Manipur",
    title: "CEREMONIAL EMBLEM",
    desc: "A symbolic textile system where authority and meaning are expressed through black fields, red boundaries, and ranked emblematic forms.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/ceremonial-emblem.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "channapatnatoys",
    name: "Karnataka",
    title: "CHANNAPATNA TOYS",
    desc: "A traditional craft of lathe-turned wooden toys finished with glossy lacquer, known for their smooth forms and vibrant colors.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/channapatna-toys.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "coircraft",
    name: "Kerala",
    title: "COIR CRAFT",
    desc: "A natural fibre craft where coconut husk is transformed into twisted yarn and rope to create durable, functional products.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/coir-craft.avif`,
    tag: "Fibre",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bellmetalrituals",
    name: "Kerala",
    title: "BELL-METAL RITUALS",
    desc: "A sacred object tradition defined by typology-led forms like lamps and vessels, crafted in dense bell-metal for ritual use.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/bell-metal-rituals.avif`,
    tag: "Metalcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kasutiembroidery",
    name: "Karnataka",
    title: "KASUTI EMBROIDERY",
    desc: "A traditional counted-thread embroidery where geometric motifs are built through precise, knotless stitching on cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/kasuti-embroidery.avif`,
    tag: "Embroidery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "keralamural",
    name: "Kerala",
    title: "KERALA MURAL",
    desc: "A sacred painting tradition where divine figures are constructed through codified forms, expressive eyes, and a disciplined five-color system.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/kerala-mural.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "khambhatagate",
    name: "Gujarat",
    title: "KHAMBHAT AGATE",
    desc: "A traditional stone craft where raw agate is shaped, drilled, and polished to reveal natural banding and translucency.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/khambhat-agate.avif`,
    tag: "Stonecraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kinhalcraft",
    name: "Karnataka",
    title: "KINHAL CRAFT",
    desc: "A traditional craft where wooden forms are built through additive shaping and finished with painted symbolic identity.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/kinhal-craft.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kolhapurjewellery",
    name: "Maharashtra",
    title: "KOLHAPUR JEWELLERY",
    desc: "A traditional metal craft where ornaments are built through linked units, articulation, and body-bound placement.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/kolhapur-jewellery.avif`,
    tag: "Jewellery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kolhapurichappal",
    name: "Maharashtra",
    title: "KOLHAPURI CHAPPAL",
    desc: "A traditional leather footwear system built through sole-first construction, strap geometry, and grounded body-fit logic.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/kolhapuri-chappal.avif`,
    tag: "Footwear",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kolhapurisaaj",
    name: "Maharashtra",
    title: "KOLHAPURI SAAJ",
    desc: "A traditional necklace system where symbolic pendants are arranged in a structured sequence across the neckline.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/kolhapuri-saaj.avif`,
    tag: "Jewellery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "lambaniembroidery",
    name: "Karnataka",
    title: "LAMBANI EMBROIDERY",
    desc: "A traditional textile craft where surfaces are constructed through patchwork, mirrors, dense stitching, and attached ornamentation.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/lambani-embroidery.avif`,
    tag: "Embroidery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "leathertoys",
    name: "Madhya Pradesh (Indore)",
    title: "LEATHER TOYS",
    desc: "A traditional craft where figures are built on armature structures and covered with stretched leather, finished with painted details.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/leather-toys.avif`,
    tag: "Toys",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "paithani",
    name: "Maharashtra",
    title: "PAITHANI",
    desc: "A handwoven silk-and-zari textile defined by pallu dominance, structural borders, and intricate loom-woven motifs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/paithani.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pawndum",
    name: "Mizoram",
    title: "PAWNDUM",
    desc: "A traditional dark-ground wrap cloth defined by bold woven stripes, panel construction, and socially coded lower-body use.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/pawndum.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "poshinaterracotta",
    name: "Gujarat",
    title: "POSHINA TERRACOTTA",
    desc: "A votive clay tradition where terracotta horses are offered at shrines as symbols of faith, protection, and fulfilled vows.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/poshina-terracotta.avif`,
    tag: "Terracotta",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "prestigependants",
    name: "Nagaland",
    title: "PRESTIGE PENDANTS",
    desc: "Body-worn symbolic forms representing status, bravery, and inherited identity through visible focal signs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/prestige-pendants.avif`,
    tag: "Jewellery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "puanchei",
    name: "Mizoram",
    title: "PUANCHEI",
    desc: "A vibrant ceremonial textile defined by bold woven bands, strong color contrasts, and rhythmic horizontal structure.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/puanchei.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "puanlaisen",
    name: "Mizoram",
    title: "PUANLAISEN",
    desc: "A traditional woven textile defined by a dominant central red band that structures the entire cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/puanlaisen.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sandalwoodcarving",
    name: "Karnataka (Mysuru)",
    title: "SANDALWOOD CARVING",
    desc: "A delicate woodcraft tradition known for intricate hand-carved details, fine relief work, and precious sandalwood material.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/sandalwood-carving.avif`,
    tag: "Woodcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sankhedawoodwork",
    name: "Gujarat (Vadodara)",
    title: "SANKHEDA WOODWORK",
    desc: "A traditional furniture craft defined by turned wooden forms, lacquered surfaces, and hand-painted motifs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/sankheda-woodwork.avif`,
    tag: "Woodcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "ganjifa-sawantwadi",
    name: "Maharashtra (Sawantwadi)",
    title: "GANJIFA",
    desc: "A traditional hand-painted card art defined by circular composition, symbolic figures, and structured decorative borders.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/ganjifa.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sawantwadiwoodcraft",
    name: "Maharashtra",
    title: "SAWANTWADI WOODCRAFT",
    desc: "A traditional miniature craft where hand-carved wooden forms are painted and arranged into playful object-world sets.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/sawantwadi-woodcraft.avif`,
    tag: "Woodcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "shapheelanphee",
    name: "Manipur",
    title: "SHAPHEE LANPHEE",
    desc: "A ceremonial honour cloth defined by black field authority, red borders, and symbolic motifs representing status and tradition.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/shaphee-lanphee.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sheerfieldcloth",
    name: "Manipur",
    title: "SHEER FIELD CLOTH",
    desc: "A soft upper-wrap textile system defined by translucency, gentle drape, and poised visual presence.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/sheer-field-cloth.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bodyaugmentation",
    name: "Nagaland",
    title: "BODY AUGMENTATION",
    desc: "A cultural system where tattoos, hair, and feathers transform the body into a symbolic and socially coded visual field.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/body-augmentation.avif`,
    tag: "Tattoo",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "tawlhlophuan",
    name: "Mizoram",
    title: "TAWLHLOHPUAN",
    desc: "A traditional warrior cloth defined by joined construction, firm woven structure, and symbolic red-white seam discipline.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/tawlhlohpuan.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "templemural",
    name: "Karnataka (Hampi)",
    title: "TEMPLE MURAL",
    desc: "A sacred architectural painting tradition where narrative panels, divine figures, and ornamental borders are integrated into temple ceilings.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/temple-mural.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "togalugombeyaata",
    name: "Karnataka",
    title: "TOGALU GOMBEYAATA",
    desc: "A traditional shadow-puppetry form where translucent leather figures, light, and screen create dynamic storytelling.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/togalu-gombeyaata.avif`,
    tag: "Puppetry",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "nagashawl",
    name: "Nagaland",
    title: "NAGA SHAWL",
    desc: "A tribe-specific woven system where pattern, structure, and identity are governed by a single coherent visual code.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/tribe-signature-shawl-branch-nagaland.avif`,
    tag: "Shawl",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "wangkheiphee",
    name: "Manipur",
    title: "WANGKHEI PHEE",
    desc: "A delicate woven textile defined by airy muslin-like body fields, sparse motifs, and strong geometric borders.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/wangkhei-phee.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "meritshawl",
    name: "Nagaland",
    title: "MERIT SHAWL",
    desc: "An earned ceremonial textile defined by bold segmented patterns, strong contrast, and public status symbolism.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/merit-shawl.avif`,
    tag: "Shawl",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "ganjifa-mysore",
    name: "Karnataka (Mysore)",
    title: "GANJIFA CARDS",
    desc: "A traditional hand-painted card system featuring miniature symbolic imagery organized within bounded fields and deck-based themes.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/ganjifa-cards.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.9) saturate(0.95)",
  },
  {
    id: "garoweaving",
    name: "Meghalaya",
    title: "GARO WEAVING",
    desc: "A traditional weaving system where border hierarchy and symbolic motifs structure cloth designed for body-wrapped garments.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/garo-weaving.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "nagabodycloth",
    name: "Nagaland",
    title: "NAGA BODY-CLOTH",
    desc: "A ceremonial textile system where identity and social role are expressed through the placement and structure of body-worn cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/naga-body-cloth.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "gondpainting",
    name: "Madhya Pradesh",
    title: "GOND PAINTING",
    desc: "A traditional art form where living beings are created through rhythmic dots and lines, expressing nature, mythology, and inner life.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/gond-painting.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "hardornament",
    name: "Nagaland",
    title: "HARD ORNAMENT",
    desc: "A body-extension system where rigid encircling forms define limb zones and reinforce the human silhouette.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/hard-ornament.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "himroo",
    name: "Maharashtra",
    title: "HIMROO",
    desc: "A courtly weaving tradition from Aurangabad featuring intricate silk and cotton patterns rooted in Deccani heritage.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/himroo.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "hmaram",
    name: "Mizoram",
    title: "HMARAM",
    desc: "A distinctive Mizo textile defined by indigo-white contrast and precise triangular motifs woven on back-strap looms.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/hmaram.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "hoysalarelief",
    name: "Karnataka",
    title: "HOYSALA RELIEF",
    desc: "An architectural sculpture tradition featuring dense, multi-tiered soapstone carvings and star-shaped structural plans.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/hoysala-relief.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "jaintiatextile",
    name: "Meghalaya",
    title: "JAINTIA TEXTILE",
    desc: "A complex weaving tradition defined by field-and-zone order, checkered patterns, and ritual shawl hierarchies.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/jaintia-textile.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "jhabuadolls",
    name: "Madhya Pradesh",
    title: "JHABUA DOLLS",
    desc: "Handcrafted stuffed-cloth dolls that record tribal life through painted features and miniature ritual ornaments.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/jhabua-dolls.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "maheshwari",
    name: "Madhya Pradesh",
    title: "MAHESHWARI",
    desc: "A lightweight handloom textile defined by body–border–pallu hierarchy, refined weave, and graceful drape.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/maheshwari.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "mashruweaving",
    name: "Gujarat",
    title: "MASHRU WEAVING",
    desc: "A traditional silk-cotton textile where warp-faced weaving creates vibrant stripes and a soft luminous surface.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/mashru-weaving.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "moirangphee",
    name: "Manipur",
    title: "MOIRANG PHEE",
    desc: "A traditional textile where the Moirang Pheejin border motif is woven through extra-weft technique, defining the identity of the cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/moirang-phee.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "motibharat",
    name: "Gujarat",
    title: "MOTI BHARAT",
    desc: "A traditional beadwork craft where surfaces are built through dense bead placement, forming contour, color, and texture.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/moti-bharat.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "mysorepainting",
    name: "Karnataka",
    title: "MYSORE PAINTING",
    desc: "A courtly painting tradition known for its delicate gesso work, gold foil application, and refined iconographic detail.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/mysore-painting.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "rosewoodinlay",
    name: "Karnataka",
    title: "ROSEWOOD INLAY",
    desc: "A meticulous woodwork craft where intricate patterns of ivory, bone, or contrasting wood are embedded into rosewood surfaces.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/rosewood-inlay.avif`,
    tag: "Woodwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "nagashawlordinary",
    name: "Nagaland",
    title: "NAGA SHAWL (ORDINARY)",
    desc: "A community-specific handwoven textile defined by bold stripe patterns and extra-weft motifs that encode ancestral lineage.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/naga-shawl-ordinary.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "ngotekherh",
    name: "Mizoram",
    title: "NGOTEKHERH",
    desc: "A traditional handwoven textile known for its distinctive warp-stripe structure and rhythmic extra-weft patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/ngotekherh.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "nironalacquer",
    name: "Gujarat (Kutch)",
    title: "NIRONA LACQUER",
    desc: "A traditional lac-turned woodcraft where vibrant natural colors are built into smooth, durable, and lustrous surfaces.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/nirona-lacquer.avif`,
    tag: "Woodcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "opaquewrap",
    name: "Mizoram",
    title: "OPAQUE WRAP",
    desc: "A traditional textile system where body-wrapped garments are defined by dense weave and bold symbolic motifs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/opaque-wrap.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "woodcarving",
    name: "Uttar Pradesh",
    title: "WOOD CARVING",
    desc: "A traditional woodwork craft known for its deep relief carving, geometric patterns, and fine handcrafted detail.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/wood-carving.avif`,
    tag: "Woodwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "wroughtiron",
    name: "Chhattisgarh",
    title: "WROUGHT IRON",
    desc: "A traditional hand-forged metalcraft where raw iron is shaped into ritual and symbolic forms.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/wrought-iron.avif`,
    tag: "Metalcraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "yakshagana",
    name: "Karnataka",
    title: "YAKSHAGANA",
    desc: "A traditional theatre art known for its bold headgear, vibrant costumes, and expressive makeup.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}next-styles-images/yakshagana.avif`,
    tag: "Art/Theatre",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "baghembroidery",
    name: "Punjab",
    title: "BAGH EMBROIDERY",
    desc: "A dense embroidered textile tradition where silk-thread stitches fully saturate the cloth, creating luminous patterned fields.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/bagh-embroidery.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bagruprint",
    name: "Rajasthan",
    title: "BAGRU PRINT",
    desc: "A traditional block-print textile defined by natural dyes, rhythmic repetition, and cloth-based design logic.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/bagru-print.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bandhej",
    name: "Rajasthan",
    title: "BANDHEJ",
    desc: "A resist tie-dye textile where tied points create vibrant dot patterns through controlled dye absorption.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/bandhej.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "berhampurpatta",
    name: "Odisha",
    title: "BERHAMPUR PATTA",
    desc: "A heritage silk weaving tradition defined by vibrant color blocks and refined temple-border motifs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/berhampur-patta.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bomkai",
    name: "Odisha",
    title: "BOMKAI",
    desc: "A handloom textile where supplementary-weft motifs create symbolic narratives within a structured border-field composition.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/bomkai.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "buddhistmask",
    name: "Sikkim",
    title: "BUDDHIST MASK",
    desc: "A ritual craft where wooden or clay masks are sculpted with bold symbolic expressions for sacred performances.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/buddhist-mask.avif`,
    tag: "Mask",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sikkimcarpet",
    name: "Sikkim",
    title: "SIKKIM CARPET",
    desc: "A traditional hand-knotted wool craft where dense pile surfaces are built with symbolic geometric and floral motifs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/sikkim-carpet.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "durrie",
    name: "Punjab",
    title: "DURRIE",
    desc: "A flat-woven textile tradition defined by geometric clarity, durable cotton or wool structures, and rhythmic patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/durrie.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "thangka-folk",
    name: "Sikkim",
    title: "THANGKA",
    desc: "A sacred Buddhist painting tradition on cotton or silk, representing a structured cosmic diagram with central hierarchy and symbolic geometry.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/thangka.avif`,
    tag: "Sacred",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "punjabjutti",
    name: "Punjab",
    title: "PUNJAB JUTTI",
    desc: "A traditional leather footwear craft where surfaces are built through dense embroidery, forming contour, color, and texture.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/punjab-jutti.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kathputli",
    name: "Rajasthan",
    title: "KATHPUTLI",
    desc: "A traditional string puppet craft from Rajasthan, featuring carved wooden heads and vibrant textile-based character design.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/kathputli.avif`,
    tag: "Puppetry",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "khaddar",
    name: "Punjab",
    title: "KHADDAR",
    desc: "A traditional hand-spun and hand-woven textile defined by its coarse texture, breathability, and rustic material integrity.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/khaddar.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "khandua",
    name: "Odisha",
    title: "KHANDUA",
    desc: "A ritual ikat silk textile from Odisha, featuring extra-weft temple borders and symbolic motifs woven into a structured field.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/khandua.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "khes",
    name: "Punjab",
    title: "KHES",
    desc: "A traditional geometric cotton textile defined by its multi-layered weave, bold checkered patterns, and functional durability.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/khes.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "malerkotlazari",
    name: "Punjab",
    title: "MALERKOTLA ZARI",
    desc: "A specialized metallic embroidery tradition where gold and silver threads are used to create intricate, luminous surface designs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/malerkotla-zari.avif`,
    tag: "Embroidery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "molela",
    name: "Rajasthan",
    title: "MOLELA",
    desc: "A traditional terracotta craft where religious and social narratives are sculpted in relief on flat clay panels.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/molela.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pichhwai",
    name: "Rajasthan",
    title: "PICHHWAI",
    desc: "A ritual textile painting tradition depicting Krishna narratives through large-scale, detailed compositions on cloth.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/pichhwai.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pattachitra",
    name: "Odisha",
    title: "PATTACHITRA",
    desc: "A traditional scroll painting style from Odisha, known for its fine line work, mythological themes, and natural pigment colors.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/pattachitra.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pipili",
    name: "Odisha",
    title: "PIPILI",
    desc: "A traditional appliqué craft from Odisha where colored fabric shapes are stitched onto a base cloth to create bold symbolic patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/pipili.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "rajasthaniminiature",
    name: "Rajasthan",
    title: "RAJASTHANI MINIATURE",
    desc: "A court painting tradition known for its fine detail, vibrant colors, and refined narrative storytelling in miniature form.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/rajasthani-miniature.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sambalpuribandha",
    name: "Odisha",
    title: "SAMBALPURI BANDHA",
    desc: "A complex ikat weaving tradition from Odisha where patterns are created through precision tie-dyeing of warp and weft threads.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/sambalpuri-bandha.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sanganer",
    name: "Rajasthan",
    title: "SANGANER",
    desc: "A traditional block-print style from Rajasthan known for its fine floral patterns, light backgrounds, and delicate design logic.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/sanganer.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "ustaart",
    name: "Rajasthan",
    title: "USTA ART",
    desc: "A traditional craft system encompassing gold-leaf work (Usta), gold embossing (Thewa), and blue-on-white ceramic imagery (Blue Pottery).",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/usta-art.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pipiliapplique",
    name: "Odisha",
    title: "PIPILI APPLIQUÉ",
    desc: "A traditional appliqué craft from Odisha where colored fabric shapes are stitched onto a base cloth to create bold symbolic patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/pipili-appliqué.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "saura",
    name: "Odisha",
    title: "SAURA",
    desc: "A ritual wall painting tradition of the Saura tribe, featuring stick-figure motifs that record tribal life and mythology in a rhythmic field.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}third-images/saura.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "banarasmural",
    name: "Uttar Pradesh",
    title: "BANARAS MURAL",
    desc: "A sacred wall-painting tradition where devotional imagery is embedded into architectural surfaces.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/banaras-mural.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "banarasibrocade",
    name: "Uttar Pradesh",
    title: "BANARASI BROCADE",
    desc: "A woven silk tradition where intricate patterns emerge directly from the loom using zari threads.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/banarasi-brocade.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "banjaraembroidery",
    name: "Telangana",
    title: "BANJARA EMBROIDERY",
    desc: "A vibrant textile tradition where mirrors, stitches, and patchwork come together to create bold geometric surfaces.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/banjara-embroidery.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "patachitra",
    name: "West Bengal",
    title: "PATA CHITRA",
    desc: "A storytelling painting tradition where vivid scenes unfold through bold lines and expressive figures.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/pata-chitra.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bhotiaweaving",
    name: "Uttarakhand",
    title: "BHOTIA WEAVING",
    desc: "A high-altitude wool weaving tradition designed for warmth, durability, and rugged mountain life.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/bhotia-weaving.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "cheriyal",
    name: "Telangana",
    title: "CHERIYAL",
    desc: "A painted scroll tradition where stories unfold through bold figures on a striking red background.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/cheriyal.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "chikankari",
    name: "Uttar Pradesh",
    title: "CHIKANKARI",
    desc: "A delicate hand embroidery tradition known for its fine stitches and graceful white-on-white elegance.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/chikankari.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "cholabronze",
    name: "Tamil Nadu",
    title: "CHOLA BRONZE",
    desc: "A sacred casting tradition where divine forms are shaped through precise proportions and timeless bronze craftsmanship.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/chola-bronze.avif`,
    tag: "Sculpture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "cholaoldbronze",
    name: "Tamil Nadu",
    title: "CHOLA OLD BRONZE",
    desc: "A sacred casting tradition where divine forms emerge through precise proportions and ritual bronze craftsmanship.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/chola-old-bronze.avif`,
    tag: "Sculpture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "farrukhabadprint",
    name: "Uttar Pradesh",
    title: "FARRUKHABAD PRINT",
    desc: "A hand block-printing tradition where patterns emerge through rhythmic repetition and carved motifs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/farrukhabad-print.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "odishafiligree",
    name: "Cuttack",
    title: "ODISHA FILIGREE",
    desc: "A delicate silver craft where intricate forms are built through fine wire and openwork precision.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/odisha-filigree.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "gadwalsaree",
    name: "Telangana",
    title: "GADWAL SAREE",
    desc: "A handloom tradition where sarees are constructed through bold contrasts and intricate woven joins.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/gadwal-saree.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "gollabhamasaree",
    name: "Telangana (Siddipet)",
    title: "GOLLABHAMA SAREE",
    desc: "A handloom tradition where iconic milkmaid motifs are woven into the fabric through extra-weft craftsmanship.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/gollabhama-saree.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "gotazari",
    name: "Rajasthan",
    title: "GOTA ZARI",
    desc: "A ceremonial textile craft where metallic elements are cut, folded, and stitched onto fabric to create radiant patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/gota-zari.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kaavad",
    name: "Rajasthan",
    title: "KAAVAD",
    desc: "A portable storytelling shrine where narratives unfold through painted wooden panels and sacred reveals.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/kaavad.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kalighatpainting",
    name: "West Bengal",
    title: "KALIGHAT PAINTING",
    desc: "A bold urban painting style defined by sweeping brush strokes, simplified figures, and striking visual clarity.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/kalighat-painting.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "karuppurkalamkari",
    name: "Tamil Nadu",
    title: "KARUPPUR KALAMKARI",
    desc: "A ceremonial painted textile tradition where sacred imagery is created through kalam-drawn lines and natural dye processes.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/karuppur-kalamkari.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kolamgeometry",
    name: "Tamil Nadu",
    title: "KOLAM GEOMETRY",
    desc: "A ritual ground art where continuous lines flow through geometric grids to create auspicious threshold patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/kolam-geometry.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "lacbangles",
    name: "Telangana",
    title: "LAC BANGLES",
    desc: "A vibrant ornament tradition where heated lac is shaped into bangles and adorned with rhythmic stone patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/lac-bangles.avif`,
    tag: "Ornament",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "maduraisungudi",
    name: "Tamil Nadu",
    title: "MADURAI SUNGUDI",
    desc: "A resist-dyed cotton tradition where tiny tied dots create rhythmic patterns across vibrant fabric.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/madurai-sungudi.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "mahabalipuramsculpture",
    name: "Tamil Nadu",
    title: "MAHABALIPURAM SCULPTURE",
    desc: "A monumental stone tradition where sacred narratives are carved directly into living granite through rock-cut mastery.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/mahabalipuram-sculpture.avif`,
    tag: "Sculpture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "narayanpetsaree",
    name: "Telangana",
    title: "NARAYANPET SAREE",
    desc: "A handloom saree tradition defined by woven checks, strong borders, and a distinct structural pallu.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/narayanpet-saree.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "nirmalart",
    name: "Telangana",
    title: "NIRMAL ART",
    desc: "A refined painted-wood tradition known for its smooth surfaces, elegant motifs, and signature gold detailing.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/nirmal-art.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bamboocanecraft",
    name: "North East",
    title: "BAMBOO & CANE CRAFT",
    desc: "A traditional weaving craft where bamboo and cane are shaped into functional forms and rhythmic structures.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/bamboo--cane-craft.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "odishastonecarving",
    name: "Odisha",
    title: "ODISHA STONE CARVING",
    desc: "An ancient stone-carving tradition where sacred forms and temple narratives are sculpted in relief and monumental scale.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/odisha-stone-carving.avif`,
    tag: "Sculpture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pachra",
    name: "Tripura",
    title: "PACHRA",
    desc: "A traditional handwoven textile from Tripura, defined by its specific cultural motifs and rhythmic weaving patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/pachra.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pembarthimetalcraft",
    name: "Telangana",
    title: "PEMBARTHI METAL CRAFT",
    desc: "An ancient metalwork tradition where brass and copper surfaces are adorned with intricate deep-relief hand carvings.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/pembarthi-metal-craft.avif`,
    tag: "Metalwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "pilkhuwablockprint",
    name: "Uttar Pradesh",
    title: "PILKHUWA BLOCK PRINT",
    desc: "A traditional hand-block printing style from Uttar Pradesh, known for its distinct rhythmic patterns and floral compositions.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/pilkhuwa-block-print.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "rangwalipichhoda",
    name: "Uttarakhand",
    title: "RANGWALI PICHHODA",
    desc: "A traditional ceremonial veil from Uttarakhand, characteristically adorned with auspicious symbols and vibrant dotted patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/rangwali-pichhoda.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "rignai",
    name: "Tripura",
    title: "RIGNAI",
    desc: "A traditional handwoven lower garment from Tripura, featuring complex geometric patterns and cultural symbolism.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/rignai.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "risa",
    name: "Tripura",
    title: "RISA",
    desc: "A traditional handwoven upper cloth from Tripura, used as ceremonial headgear and a symbol of cultural honor.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/risa.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sanjhi",
    name: "Uttar Pradesh",
    title: "SANJHI",
    desc: "A sacred paper-cutting tradition from Mathura, where intricate stencils are used to create devotional art and threshold patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/sanjhi.avif`,
    tag: "Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "tamilritualcraft",
    name: "Tamil Nadu",
    title: "TAMIL RITUAL CRAFT",
    desc: "A broad category of ceremonial crafts from Tamil Nadu, designed for sacred temple rituals and festive processions.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/tamil-ritual-craft.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "tanjorepainting",
    name: "Tamil Nadu",
    title: "TANJORE PAINTING",
    desc: "A classical painting style from Tamil Nadu, known for its rich colors, gold-leaf embellishments, and sacred iconography.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/tanjore-painting.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "thanjavurdoll",
    name: "Tamil Nadu",
    title: "THANJAVUR DOLL",
    desc: "A traditional bobblehead craft from Tamil Nadu, featuring handmade terracotta forms that move with a distinct rhythmic grace.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/thanjavur-doll.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "therukoothu",
    name: "Tamil Nadu",
    title: "THERUKOOTHU",
    desc: "An ancient folk theatre tradition from Tamil Nadu, where sacred epics are enacted through music, dance, and vibrant costume design.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/therukoothu.avif`,
    tag: "Folk Theatre",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "todaembroidery",
    name: "Tamil Nadu",
    title: "TODA EMBROIDERY",
    desc: "A unique reversible embroidery tradition from the Nilgiris, featuring precise geometric patterns in red and black wool.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/toda-embroidery.avif`,
    tag: "Embroidery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "zardozi",
    name: "Uttar Pradesh",
    title: "ZARDOZI",
    desc: "An opulent metallic embroidery tradition where gold and silver threads are used to create intricate surface patterns on rich fabrics.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}4th-images/zardozi.avif`,
    tag: "Embroidery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "gabba",
    name: "Kashmir",
    title: "GABBA",
    desc: "A traditional floor covering made from reconstructed blankets, enriched with stitched and appliqué designs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/gabba.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "garadsaree",
    name: "West Bengal",
    title: "GARAD SAREE",
    desc: "A ceremonial silk tradition defined by its pure off-white body, bold red border, and refined simplicity.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/garad-saree.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "himalayansacredimage",
    name: "Ladakh",
    title: "HIMALAYAN SACRED IMAGE",
    desc: "A ritual visual system where sacred figures are constructed through iconography, symbolism, and meditative hierarchy.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/himalayan-sacred-image.avif`,
    tag: "Ritual Art",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "khatamband",
    name: "Kashmir",
    title: "KHATAMBAND",
    desc: "A traditional ceiling craft where interlocking wooden units form a continuous geometric architectural system.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/khatamband.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "kushmandimask",
    name: "West Bengal",
    title: "KUSHMANDI MASK",
    desc: "A ritual wooden mask tradition where carved faces embody deities, demons, and mythic characters in performance.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/kushmandi-mask.avif`,
    tag: "Ritual",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "likhaiwoodcarving",
    name: "Uttarakhand",
    title: "LIKHAI WOOD CARVING",
    desc: "A traditional carving technique where forms are sculpted from solid wood through measured, hand-carved structure.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/likhai-wood-carving.avif`,
    tag: "Woodwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "matweaving",
    name: "Daman & Diu",
    title: "MAT WEAVING",
    desc: "A traditional craft where plant fibers are interlaced to create flat, structured mats with woven patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/mat-weaving.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "moradabadmetalcraft",
    name: "Uttar Pradesh",
    title: "MORADABAD METAL CRAFT",
    desc: "A traditional brassware craft where cast metal forms are refined through intricate hand-worked detailing.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/moradabad-metal-craft.avif`,
    tag: "Metalwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "namda",
    name: "Kashmir",
    title: "NAMDA",
    desc: "A traditional felted wool craft where compressed fibers form a dense rug, enriched with surface embroidery.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/namda.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "needlework",
    name: "Lakshadweep",
    title: "NEEDLE WORK",
    desc: "A practical textile tradition where cloth is constructed through seams, joins, and simple hand stitching.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/needle-work.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "palmmat",
    name: "Andaman & Nicobar",
    title: "PALM MAT",
    desc: "A traditional craft where pandanus leaves and coconut strips are interwoven to form flat, functional mats.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/palm-mat.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "papiermachekashmir",
    name: "Kashmir",
    title: "PAPIER-MÂCHÉ",
    desc: "A refined paper craft where molded forms are polished and richly decorated with intricate floral designs.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/papier-mch.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "puruliachhaumask",
    name: "West Bengal",
    title: "PURULIA CHHAU MASK",
    desc: "A traditional performance mask where exaggerated faces and elaborate headdresses bring mythological characters to life.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/purulia-chhau-mask.avif`,
    tag: "Ritual",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "papiermachepuducherry",
    name: "Puducherry",
    title: "PAPIER-MÂCHÉ",
    desc: "A handcrafted tradition where lightweight paper pulp is shaped into simple, expressive objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/papier-mchpuducherry.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "rammanmask",
    name: "Uttarakhand",
    title: "RAMMAN MASK",
    desc: "A sacred wooden mask tradition where faces are carved from solid wood and used in ritual performances.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/ramman-mask.avif`,
    tag: "Ritual",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "rockgardenassemblage",
    name: "Chandigarh",
    title: "ROCK GARDEN ASSEMBLAGE",
    desc: "A unique environment where discarded materials are transformed into a continuous sculptural world.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/rock-garden-assemblage.avif`,
    tag: "Sculpture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "saharanpurwoodcraft",
    name: "Uttar Pradesh",
    title: "SAHARANPUR WOOD CRAFT",
    desc: "A traditional wood carving craft where intricate floral and geometric designs are sculpted into solid wood.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/saharanpur-wood-craft.avif`,
    tag: "Woodwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "shellcraft",
    name: "Andaman & Nicobar",
    title: "SHELL CRAFT",
    desc: "A coastal craft where natural seashells are assembled into compact, handcrafted objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/shell-craft.avif`,
    tag: "Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "sozniembroidery",
    name: "Kashmir",
    title: "SOZNI EMBROIDERY",
    desc: "A fine needle embroidery tradition where delicate stitches create intricate floral and paisley patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/sozni-embroidery.avif`,
    tag: "Embroidery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "terracottacraft",
    name: "Puducherry",
    title: "TERRACOTTA CRAFT",
    desc: "A traditional craft where clay is shaped and fired to create durable, earthy objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/terracotta-craft.avif`,
    tag: "Pottery",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "walnutcarving",
    name: "Kashmir",
    title: "WALNUT CARVING",
    desc: "A traditional woodcraft where solid walnut is intricately carved into deep relief patterns.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/walnut-carving.avif`,
    tag: "Woodwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "woodcraft",
    name: "Andaman & Nicobar",
    title: "WOODCRAFT",
    desc: "A handcrafted tradition where solid timber is shaped into simple, expressive objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/woodcraft.avif`,
    tag: "Woodwork",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "ladakhtextilesystem",
    name: "Ladakh",
    title: "LADAKH TEXTILE SYSTEM",
    desc: "A fiber-based tradition where wool, yak hair, and textiles form functional objects, shelter, and ritual systems.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/ladakh-textile-system.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "indoportugueseenvironment",
    name: "Daman & Diu",
    title: "INDO-PORTUGUESE ENVIRONMENT",
    desc: "A fortified coastal settlement where churches, gateways, and walls form a unified architectural system.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/indo-portuguese-environment.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "agramarbleinlay",
    name: "Uttar Pradesh",
    title: "AGRA MARBLE INLAY",
    desc: "A Mughal-rooted stone inlay tradition where semi-precious stones are fitted into engraved marble bases.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/agra-marble-inlay.avif`,
    tag: "Stone Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "balucharisaree",
    name: "West Bengal",
    title: "BALUCHARI SAREE",
    desc: "A narrative silk-weaving tradition from West Bengal featuring mythological and social-historical motifs on the pallu.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/baluchari-saree.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "bankuraterracotta",
    name: "West Bengal",
    title: "BANKURA TERRACOTTA",
    desc: "A fired-clay sculptural tradition from West Bengal, famous for its stylized horses and ritual objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/bankura-terracotta.avif`,
    tag: "Terracotta",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "basohlipainting",
    name: "Jammu",
    title: "BASOHLI PAINTING",
    desc: "A bold Pahari miniature tradition from Jammu, characterized by primary colors, large eyes, and expressive intensity.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/basohli-painting.avif`,
    tag: "Painting",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "canebamboocraftandaman",
    name: "Andaman & Nicobar",
    title: "CANE & BAMBOO CRAFT",
    desc: "A construction-based island tradition where split strips and bent members form functional and decorative objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/cane-bamboo-craft.avif`,
    tag: "Bamboo & Cane",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "chandigarhmodernist",
    name: "Chandigarh",
    title: "CHANDIGARH MODERNIST",
    desc: "A planned civic-modernist architectural style defined by exposed concrete, formal geometry, and green-city openness.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/chandigarh-modernist.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "coastalfibercraft",
    name: "Lakshadweep",
    title: "COASTAL FIBER CRAFT",
    desc: "An island fiber-craft system from Lakshadweep using coconut coir and leaf-weaving for functional objects.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/coastal-fiber-craft.avif`,
    tag: "Fiber Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "coconutshellcraft",
    name: "Andaman & Nicobar",
    title: "COCONUT SHELL CRAFT",
    desc: "A compact handcrafted tradition where coconut shells are shaped and polished into utility and decorative articles.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/coconut-shell-craft.avif`,
    tag: "Handicraft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "coircraftlakshadweep",
    name: "Lakshadweep",
    title: "COIR CRAFT",
    desc: "A rugged fiber-craft tradition using coconut husk coir for rope-making, matting, and utility basketry.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/coir-craft.avif`,
    tag: "Fiber Craft",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "dhaniakhalisaree",
    name: "West Bengal",
    title: "DHANIAKHALI SAREE",
    desc: "A distinctive cotton-weaving tradition from West Bengal known for its dense texture and contrast borders.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/dhaniakhali-saree.avif`,
    tag: "Textile",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
  {
    id: "francotamilenvironment",
    name: "Puducherry",
    title: "FRANCO-TAMIL ENVIRONMENT",
    desc: "A hybrid architectural system from Puducherry merging French colonial facades with Tamil house morphologies.",
    image: `${CREATIVE_STYLE_IMAGE_BASE}5th-images/franco-tamil-environment.avif`,
    tag: "Architecture",
    titleColor: "#ffffff",
    href: "/text-to-image",
    imageFilter: "brightness(0.85) saturate(0.95)",
  },
];

export const STYLES: StyleItem[] = rawStyles.map((style) => ({
  ...style,
  state: style.state ?? inferStyleState(style.name),
  typeId: style.typeId ?? inferStyleTypeId(style.tag),
}));
