export const kangraPromptV3 = {
  promptHard: `Create a fully volumetric cinematic world generated by Kangra painting logic from Himachal Pradesh, where the whole reality feels born from delicate line, serene figures, soft lyrical color, lush green landscape, and poetic-devotional image intelligence rather than merely decorated by miniature-style surface cues.
Do not assume prior knowledge of the style. The core system is this:
Kangra is a late Pahari lyrical painting tradition associated with refined delicate line, soft less-intense colors, serene graceful human types, lush greenery, and Krishna-centered poetic-devotional themes.
This version must not become:
realistic Indian historical fantasy
generic romantic miniature world
cinematic realism with Kangra costume accents
green scenic realism with miniature faces
devotional poster realism
Instead, let the entire world be generated by Kangra pictorial intelligence.
WHOLE-FRAME WORLD RULE:
Every visible element must belong to the same Kangra-built world.
figures must be Kangra-built in face, body, posture, and emotional reading
gestures must be lyrical and rasa-bearing
landscape must be Kangra landscape in form, spacing, vegetation, and emotional tone
architecture must belong to miniature-painting logic, not realism architecture
color must remain soft, fresh, lyrical, and painting-led
shadow must remain softened and integrated into pictorial structure
grouping must remain poetic and devotional / romantic, not staged like realism cinema
no important element may remain realism-first underneath
ORIGIN-SYSTEM MEMORY RULE:
Even in a fully cinematic world, the image must still visibly remember:
delicate line
serene stylized faces
graceful figure construction
lush green hill-garden environment
softer lyrical palette
poetic devotional painting atmosphere
SPACE RULE:
Allow full spatial depth, cinematic immersion, environmental layering, and world coherence, but keep the space generated by Kangra pictorial logic rather than realism-first camera logic.
SHADOW RULE:
Use full-world shadow only insofar as it remains subordinate to Kangra softness and pictorial emotional control. No harsh realism lighting takeover.
NEGATIVE RULE:
no realistic fantasy world with miniature styling
no texture transfer
no costume transfer
no green scenic realism
no Mughal realism drift
no generic mythological art
no hard cinematic shadow
no realism stronger than Kangra image logic
OUTPUT GOAL:
The final result must feel like Kangra painting became an inhabitable cinematic world, with full transformation of form, shadow, space, grouping, landscape, and emotion.`,
  promptVariable: `Create [SUBJECT / SCENE / POETIC WORLD / DEVOTIONAL MOMENT] as a fully volumetric cinematic world generated by Kangra painting logic.
STYLE SYSTEM:
late Pahari lyrical painting,
delicate refined line,
serene graceful figures,
soft fresh less-intense palette,
lush green landscape,
poetic-devotional / romantic atmosphere,
painting-born world structure.
WHOLE-FRAME WORLD RULE:
[MAIN FIGURE] becomes a Kangra-built volumetric focal figure
[SECONDARY FIGURES] become supporting lyrical figures in the same pictorial world
[FACES] remain serene, refined, and Kangra-specific
[GESTURES] remain poetic and rasa-bearing
[LANDSCAPE] becomes a full Kangra hill-garden world
[ARCHITECTURE / OBJECTS] become painting-born volumetric forms
[SPACE] becomes Kangra-generated world depth
[SHADOW] remains soft and pictorially integrated
[GROUPING] becomes emotionally lyrical and devotional / romantic
INCREASE:
world depth
landscape recession
environmental layering
atmospheric coherence
figure-ground relation
cinematic readability
DO NOT LOSE:
Kangra figure logic
Kangra face logic
delicate line memory
soft lyrical color
lush green landscape
poetic whole-frame unity
AVOID:
realism-first fantasy
miniature costume on realistic forms
texture styling only
generic mythological painting
hard shadow
scenic realism stronger than Kangra logic`,
  promptI2I: `Convert this source image into a fully volumetric cinematic Kangra painting world.
Preserve the source image's core emotional situation, main subject hierarchy, key narrative action, and readable scene structure, but rebuild the entire frame through:
delicate refined Kangra line logic
serene graceful Kangra face and body construction
soft fresh less-intense color
lush green lyrical environment
painting-led space
soft integrated shadow
poetic devotional / romantic grouping
Translate the whole frame:
faces into Kangra faces
bodies into Kangra figures
gestures into lyrical expressive Kangra gestures
nature into Kangra hill-garden landscape
architecture into miniature-painting architecture
space into a Kangra-built world
emotional reading into poetic rasa-led atmosphere
Do not simply apply a miniature filter.
Do not just add greenery.
Do not restyle clothing only.
Do not keep the source realism underneath.
The final result must feel like the source image was rebuilt into an inhabitable Kangra cinematic world from the base structure upward.`,
};
