export const kinnauriPromptV3 = {
  promptHard: `Create a fully volumetric cinematic textile world generated by Kinnauri shawl / weaving logic from Himachal Pradesh, where the whole object feels born from handwoven wool structure, geometric-symbolic border order, neutral field versus bright pattern contrast, and real shawl behavior rather than merely decorated by ethnic motifs.
Do not assume prior knowledge of the style. The core system is this:
Kinnauri weaving is a handloom wool textile tradition defined by elaborate geometric motifs, symbolic and religious pattern meaning, restrained grounds, brighter woven pattern colors, and strong border organization, sometimes on all four edges.
This version must not become:
generic realistic shawl with ethnic print
premium fashion accessory with Himalayan styling
Kullu-like simplified border shorthand
surface motif overlay on generic fabric
studio-fashion realism with decorative pattern
Instead, let the entire object-world be generated by Kinnauri weaving intelligence.
WHOLE-OBJECT WORLD RULE:
Every visible element must belong to the same Kinnauri-built textile world.
the cloth body must be woven in structure
motifs must be loom-built and symbolic, not printed graphics
borders must govern the object's edge identity
folds, drape, and body relation must preserve motif and border order
corners, ends, and seam behavior must remain handloom-consistent
if a wearer is present, the shawl still remains the style engine
no important element may remain generic textile realism underneath
ORIGIN-SYSTEM MEMORY RULE:
Even in a fully cinematic object-world, the result must still visibly remember:
handwoven wool structure
geometric-symbolic motif complexity
border discipline
neutral grounds
bright pattern colors
seam and edge logic
Kinnauri complexity stronger than generic mountain craft styling
SPACE RULE:
Allow full spatial depth, cinematic object presence, drape-world realism, and textile-to-body interaction, but keep the object generated by Kinnauri weave logic rather than fashion-realism logic.
SHADOW RULE:
Use cloth-supporting shadow only. No glamour lighting, no synthetic sheen, no fashion-photo studio takeover.
NEGATIVE RULE:
no print-look shawl
no generic ethnic fashion realism
no Kullu simplification
no synthetic polish
no motif overlay
no generic mountain textile styling
no realism stronger than weave structure
no decorative surface-first interpretation
OUTPUT GOAL:
The final result must feel like Kinnauri weaving became an inhabitable textile world, with full transformation of structure, motif, border, drape, seam, and object identity.`,
  promptVariable: `Create [SUBJECT / SHAWL / WEARABLE TEXTILE WORLD / DRAPED OBJECT MOMENT] as a fully volumetric cinematic textile world generated by Kinnauri weaving logic.
STYLE SYSTEM:
handwoven wool body,
elaborate geometric-symbolic motifs,
strong border-and-edge order,
neutral field / bright pattern contrast,
symbolic color structure,
shawl-first object logic,
handloom-built complexity.
WHOLE-OBJECT WORLD RULE:
[MAIN CLOTH BODY] becomes a Kinnauri-built volumetric textile field
[BORDERS] become governing structural identity zones
[MOTIFS] become woven symbolic modules
[FOLDS / DRAPE / WRAP] become Kinnauri-ordered textile behavior
[EDGES / CORNERS / SEAMS / ENDS] remain handloom-consistent
[WEARER / BODY] if present remains secondary to the shawl system
[OVERALL OBJECT] remains governed by weave logic, not fashion logic
INCREASE:
object volume
drape realism
edge coherence
border readability
textile-to-body relation
whole-object continuity
DO NOT LOSE:
woven identity
motif complexity
border discipline
ground-versus-pattern contrast
symbolic order
Kinnauri objecthood
AVOID:
generic fashion realism
printed ethnic textile
surface styling only
Kullu-like simplification
synthetic fabric feel
motif decal look`,
  promptI2I: `Convert this source image into a fully volumetric cinematic Kinnauri woven textile world.
Preserve the source image's main textile function, object hierarchy, drape behavior, and readable structure, but rebuild the entire object through:
handwoven wool structure
loom-built geometric-symbolic motifs
strong border-and-edge order
neutral ground with brighter patterned zones
seam and handloom-consistent join logic
Kinnauri-built drape and object behavior
Translate the whole object:
fabric into true woven wool
motifs into structural geometric Kinnauri pattern
borders into primary governing edge systems
folds into cloth behavior that preserves motif order
edges and corners into shawl-built structure
wearer relation into secondary support for the shawl's identity
Do not simply place Kinnauri motifs on a realistic shawl.
Do not just recolor the cloth.
Do not use print logic underneath.
Do not make it a fashion-realistic garment with decorative ethnic cues.
The final result must feel like the source image was rebuilt into a cinematic Kinnauri textile world from the base structure upward.`,
};
