export const maheshwariPromptV1 = `Create an image in the authentic visual grammar of traditional Maheshwari handloom from Madhya Pradesh. Do not treat this as generic Indian silk, generic saree styling, or a normal world with Maheshwari fabric added later. Build the entire image as if it is generated by a Maheshwari world where body-border-pallu hierarchy, reversible border logic, stripe-and-check rhythm, and lightweight woven refinement control every decision.

The image must obey Maheshwari weaving rules:
- the world is built from garment-structure logic (body-border-pallu), not scenic logic
- the border is not an edge; it is a structural zone with reversible identity
- the pallu is not a decorative end; it is a distinct hierarchical field
- stripes and checks are not surface patterns; they are the loom-born pulse of the world
- the cloth reads as lightweight, airy, and high-count, yet structurally firm
- the world feels refined, courtly (Ahilya Bai Holkar legacy), and weave-disciplined

Translate the full world through this style:
- shape must become border-led, banded, and body-field oriented
- form must become loom-disciplined and lightweight rather than heavy or pictorial
- space must become textile-space: divided into hierarchy zones (body, border, pallu) rather than ordinary perspective space
- light must reveal woven texture, reversible edge clarity, and the interplay of silk and cotton
- shadow must support cloth relief and structural divisions, not cinematic atmosphere
- value must remain clean, distinct, and hierarchy-supportive
- volume must behave as lightweight cloth volume: fine folds, delicate drape, and rhythmic tension
- movement must feel like the flow of fine handloom, border-sway, and weave-continuity
- environment must also obey Maheshwari order: architecture, foliage, ground, and background must all feel organized by stripe/check rhythm, border intelligence, and terminal pallu-like fields

Use Maheshwari anchors such as:
bugadi-style borders, reversible woven edges, distinct pallu bands, fine silk-cotton (garbh-resham) character, and Holkar-court refinement.

Avoid:
generic saree fantasy, heavy brocade styling, pictorial motifs, bulky fabric behavior, ordinary environment with only the textile changed, surface-only transformation.

The final result must feel like a true Maheshwari world: body-border-pallu based, loom-born, reversible-edge-led, lightweight, and fully translated in shape, form, space, light, hierarchy, and environment.`;