export const mashruweavingPromptV1 = `Create an image in the authentic visual grammar of traditional Mashru weaving from Gujarat. Do not treat this as generic striped silk, generic satin, or a normal world with Mashru fabric added later. Build the entire image as if it is generated by a Mashru world where warp-faced satin logic, silk-cotton mixed fiber intelligence, and vibrant stripe-and-motif rhythm control every decision.

The image must obey Mashru weaving rules:
- the world is built from warp-faced satin logic: the surface must feel silk-dominant, luminous, and smooth, while the underside (implied or visible) is cotton-rough
- stripes are not surface patterns; they are the structural warp-born pulse of the world
- the visual field must feel dense, lustrous, and tightly woven
- colors must remain vibrant and deeply saturated, characteristic of traditional Mashru (reds, yellows, blacks, and indigos)
- motifs (misri, adadiya, etc.) must behave as woven structural units within the stripes, never as painted illustrations
- the world feels durable, luxurious yet grounded, and structurally organized by warp-tension

Translate the full world through this style:
- shape must become stripe-led, banded, and warp-dominant
- form must become luminous and satin-surfaced rather than matte or generic realism
- space must become textile-space: organized by parallel bands, woven intervals, and structural sheen rather than ordinary perspective space
- light must reveal the specific directional lustre of warp-faced silk, the tight weave density, and the deep saturation of traditional dyes
- shadow must support the smooth relief and structural rhythmic bands, not cinematic atmosphere
- value must remain clean, contrasting, and stripe-supportive
- volume must behave as Mashru cloth volume: heavy satin drape, structured folds, and the specific tension of a silk-cotton mix
- movement must feel like the linear flow of stripes, the shift of warp-faced sheen, and woven continuity
- environment must also obey Mashru order: architecture, foliage, ground, and background must all feel organized by stripe rhythm, warp intelligence, and the material presence of satin-woven fields

Use Mashru anchors such as:
warp-faced satin structure, silk-cotton (mixed fiber) logic, vibrant rhythmic stripes, traditional motif units (dots, small diamonds) within bands, and the specific "permitted" (Mashru) textile heritage.

Avoid:
generic striped fashion, normal satin glamour, printed stripes, single-material logic, ordinary environment with only the textile changed, surface-only transformation.

The final result must feel like a true Mashru world: warp-faced, luminous, stripe-led, silk-cotton based, and fully translated in shape, form, space, light, hierarchy, and environment.`;