export const ngotekherhPromptV1 = `Create an image in the authentic visual grammar of traditional Ngotekherh (a traditional wrap) from Mizoram. Do not treat this as generic striped cotton, generic tribal wrap, or a normal world with Ngotekherh fabric added later. Build the entire image as if it is generated by a Ngotekherh world where the transverse black-and-white (or colored) bands, extra-weft motif sequences, and the specific "wrap-authority" of Mizo textile logic control every decision.

The image must obey Ngotekherh rules:
- the world is built from banded-field logic: the textile is defined by bold transverse bands (longitudinal when worn) that structure the visual field
- extra-weft motifs are not surface patterns; they are "woven-in" structural units, often small and geometric, arranged in rhythmic sequences across the bands
- the visual field must feel dense, hand-woven (backstrap loom character), and structurally organized by the warp-and-weft tension
- the wrap is not just a garment; it is a structural zone that defines the body's silhouette and social presence
- colors are traditionally vibrant but structured: often involving whites, blacks, and reds with specific motif-color accents
- the world feels dignified, community-bound, and structurally precise

Translate the full world through this style:
- shape must become band-led, rhythmic-sequenced, and wrap-oriented
- form must become heavy-woven and extra-weft-disciplined rather than soft or pictorial
- space must become textile-space: divided into structural color-bands and motif-sequences rather than ordinary perspective space
- light must reveal the hand-spun cotton texture, the specific relief of extra-weft motifs, and the bold saturation of traditional dyes
- shadow must support the structural divisions of the woven bands and the relief of the symbols, not cinematic atmosphere
- value must remain clean, contrasting, and hierarchy-supportive
- volume must behave as Mizo wrap volume: stiff, heavy drapes, specific tension around the body, and woven-edge clarity
- movement must feel like the rhythmic flow of horizontal bands, the steady repeat of motifs, and communal continuity
- environment must also obey Ngotekherh order: architecture, foliage, ground, and background must all feel organized by band hierarchy, motif-sequences, and the material presence of woven fields

Use Ngotekherh anchors such as:
bold transverse bands, small geometric extra-weft motif sequences, heavy hand-woven cotton texture, the specific Mizo wrap silhouette, and the dignified presence of Mizoram's textile heritage.

Avoid:
generic tribal kitch, soft-edged motifs, printed bands, single-material logic, ordinary environment with only the textile changed, surface-only transformation.

The final result must feel like a true Ngotekherh world: band-led, extra-weft-sequenced, Mizo-dignified, and fully translated in shape, form, space, light, hierarchy, and environment.`;