export const nironalacquerPromptV1 = `Create an image in the authentic visual grammar of traditional Nirona Lacquer work from Gujarat. Do not treat this as generic painted wood, generic glossy furniture, or a normal world with lacquered objects added later. Build the entire image as if it is generated by a Nirona Lacquer world where lathe-turning (rotational symmetry) and hand-applied lacquer bands control every decision.

The image must obey Nirona Lacquer rules:
- the world is built from lathe-turning logic: forms must feel turned, cylindrical, or rotationally symmetrical
- colors are applied using solid lacquer sticks against the spinning wood: they must feel like fused, glossy, vibrant bands that wrap around the form
- patterns are rotation-born: they consist of rhythmic bands, zig-zags (created by hand-manipulation while spinning), and bold color-blocks
- the visual field must feel glossy, hand-worked, and physically fused with the wooden substrate
- traditional colors are vibrant and primary: red, yellow, green, and black are common
- the world feels craft-intensive, rotational, and structurally organized by the lathe's axis

Translate the full world through this style:
- shape must become lathe-turned, cylindrical, and rotation-led
- form must become a glossy, lacquered wooden surface rather than organic or pictorial
- space must become "spinning-space": organized by rotational intervals and cylindrical massing rather than ordinary perspective space
- light must reveal the specific high-gloss sheen of hand-applied lacquer and the subtle texture of the turned wood beneath
- shadow must support the rotational volumes and the depth of the lacquer layers, not cinematic atmosphere
- value must remain bold, contrasting (band against band), and rotational-rhythm supportive
- volume must behave as turned-wood volume: cylindrical, balanced, and structurally centered
- movement must feel like the rhythmic spin of the lathe, the flow of lacquer bands, and rotational continuity
- environment must also obey Nirona order: architecture, foliage (like turned-wood trunks), ground, and background must all feel organized by rotational symmetry and glossy band logic

Use Nirona Lacquer anchors such as:
lathe-turned cylindrical forms, glossy hand-applied lacquer bands, zig-zag rotational patterns, vibrant primary color-blocking, and the specific material presence of lacquered wood.

Avoid:
generic painted wood, flat patterns, non-rotational geometry, matte surfaces, ordinary environment with only the textile changed, surface-only transformation.

The final result must feel like a true Nirona Lacquer world: lathe-turned, glossy-banded, rotation-led, and fully translated in shape, form, space, light, hierarchy, and environment.`;