export const tawlhlohpuanPromptV1 = `Create an image in the authentic visual grammar of traditional Tawlhlohpuan from Mizoram. Do not treat this as generic tribal textile, generic striped cloth, or a normal world with a Mizo wrap added later. Build the entire image as if it is generated by a Tawlhlohpuan world where the two-piece joined panel construction, red-and-white seam discipline, and warrior-merit authority control every decision.

The image must obey Tawlhlohpuan rules:
- the world is built from panel-join logic: the textile consists of two hand-woven panels stitched together, creating an essential central seam
- the visual field is dominated by a dark indigo/black ground with bold red and white bands
- the red-and-white seam is not a detail; it is the structural and symbolic spine of the cloth
- extra-weft motifs (if present) are minimal and structurally blocky, obeying the warp-and-weft discipline
- the cloth reads as heavy, firm, and physically substantial (backstrap loom character)
- the world feels dignified, warrior-rooted, and structurally organized by panel-joining and edge-containment

Translate the full world through this style:
- shape must become panel-segmented, seam-led, and field-oriented
- form must become heavy-woven and panel-disciplined rather than soft or pictorial
- space must become textile-space: divided into structural indigo-fields, red-bands, and central-seam hierarchy rather than ordinary perspective space
- light must reveal the heavy hand-spun cotton texture, the specific relief of the central seam, and the deep saturation of traditional dyes
- shadow must support the structural weight of the thick folds and the panel-join relief, not cinematic atmosphere
- value must remain bold, contrasting (red-on-indigo), and hierarchy-supportive
- volume must behave as Tawlhlohpuan volume: stiff, heavy drapes, specific body-hugging tension, and joined-panel authority
- movement must feel like the rhythmic flow of panel-joins, the steady repeat of woven bands, and communal continuity
- environment must also obey Tawlhlohpuan order: architecture, foliage, ground, and background must all feel organized by panel-hierarchy, seam geometry, and the material presence of heavy indigo-black fields

Use Tawlhlohpuan anchors such as:
two-piece joined panel construction, prominent red-and-white central seam, bold indigo-black ground, red border bands, hand-woven backstrap texture, and the specific dignified poise of Mizo warrior heritage.

Avoid:
generic tribal kitch, soft-edged motifs, single-panel logic, printed seams, ordinary environment with only the textile changed, surface-only transformation.

The final result must feel like a true Tawlhlohpuan world: panel-led, seam-disciplined, warrior-dignified, and fully translated in shape, form, space, light, hierarchy, and environment.`;