export const woodcarvingPromptV1 = `Create an image in the authentic visual grammar of traditional Naga Wood Carving from Nagaland. Do not treat this as generic wooden art, generic primitive carving, or a normal world with wooden objects added later. Build the entire image as if it is generated by a Naga Wood Carving world where bold, expressive high-relief (often monoxyle), symbolic ancestor/warrior motifs, and the specific texture of adze-cut wood control every decision.

The image must obey Naga Wood Carving rules:
- the world is built from relief-massing logic: forms are carved out of solid wooden blocks (often single logs), creating a specific, powerful high-relief character
- motifs are not decorative; they are structural and symbolic (human figures, heads, tigers, mithuns, hornbills)
- the visual field is defined by the bold, sometimes exaggerated, proportions of traditional Naga carvings: large heads, powerful limbs, and expressive features
- surfaces are not smooth; they bear the rhythmic marks of the adze and chisel, revealing the physical act of carving
- the world feels heavy, durable, rooted in warrior-prestige, and structurally organized by symbolic massing
- colors (if any) are traditional: charred black, terracotta red, and off-white, used as structural accents rather than pictorial painting

Translate the full world through this style:
- shape must become relief-massed, adze-textured, and symbol-led
- form must become a solid carved-wood presence rather than organic or pictorial
- space must become "carved-space": organized by depth of relief and structural massing rather than ordinary perspective space
- light must reveal the specific adze-cut planes, the grain-texture of traditional local woods, and the depth of the recessed areas
- shadow must support the strong structural relief and the symbolic shadows of the carved forms, not cinematic atmosphere
- value must remain bold, contrasting (high-relief against recess), and hierarchy-supportive
- volume must behave as solid wood volume: heavy, monoxyle (where appropriate), and physically substantial
- movement must feel like the rhythmic flow of carved lines, the poise of ancestor-spirits, and structural continuity
- environment must also obey Naga Wood Carving order: architecture (like morung pillars), foliage (turned into carved masses), ground, and background must all feel organized by relief logic and symbolic geometry

Use Naga Wood Carving anchors such as:
high-relief monoxyle carving, adze-chisel textures, symbolic mithun/hornbill/human motifs, morung-pillar structural logic, charred wood accents, and the specific dignified power of Naga warrior-heritage.

Avoid:
generic wooden illustration, soft-edged primitive art, pictorial carving, ordinary realism with wood filters, surface-only wood texture, decorative lighting.

The final result must feel like a true Naga Wood Carving world: relief-led, adze-textured, symbol-dignified, and fully translated in shape, form, space, light, hierarchy, and environment.`;